# # input("Give me your country name: ")
# print("hi"+', '+'baby')
# print('span '*3)
# print('2'*4)
# msg = "My self score on \nPHP: {0}, Python: {1}, Java: {2}, Swift: {3}". format(6, 7, 5, 6)

# print(msg)
# print(", ".join(["apple", "orange", "pineapple"]))
#  print("Hello ME".replace("ME", "world"))
# print("This is a sentence.".upper())
# print("AN ALL CAPS SENTENCE".lower())
# print("a, e, i, o, u".split(", "))
# user_input = input("Enter your birth year: ")
#  print(input)
